# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: about
    url: /
    weight: 1
  - name: cv
    url: /
    weight: 2
  - name: publications
    url: /#publications
    weight: 3
  - name: outreach
    url: /#outreach
    weight: 4
  - name: blog
    url: /#blog
    weight: 5
  
  
